version: '3'
services:
  request_handler:
    build: ./src/backend/apiserver
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"

  queue_processor:
    build: ./src/backend/styletransfer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network
    # comment this if your device doesn't have nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # default Redis port
    volumes:
      - redis-data:/data  # persistent storage for Redis
    networks:
      - app-network

  frontend:
    build: ./src/frontend
    depends_on:
      - request_handler
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
