version: '3'
services:
  request_handler:
    build: ./apiserver
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"

  queue_processor:
    build: ./styletransfer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # default Redis port
    volumes:
      - redis-data:/data  # persistent storage for Redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
